---
version: "3.8"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - ${DOCKER_DATA_FOLDER}/sonarr:/config
      - nas:/nas
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Sonarr"
      - "homepage.description=TV Show Collection Manager"
      - "homepage.icon=sonarr.png"
      - "homepage.href=https://sonarr.${PUBLIC_DOMAIN}/"
    restart: unless-stopped
    
  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - ${DOCKER_DATA_FOLDER}/radarr:/config
      - nas:/nas
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Radarr"
      - "homepage.description=Movie Collection Manager"
      - "homepage.icon=radarr.png"
      - "homepage.href=https://radarr.${PUBLIC_DOMAIN}/"
    restart: unless-stopped
    
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/prowlarr:/config
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Prowlarr"
      - "homepage.description=Indexers Management"
      - "homepage.icon=prowlarr.png"
      - "homepage.href=https://prowlarr.${PUBLIC_DOMAIN}/"
    restart: unless-stopped
    
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/bazarr:/config
      - nas:/nas
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Bazarr"
      - "homepage.description=Subtitles Collection Manager"
      - "homepage.icon=bazarr.png"
      - "homepage.href=https://bazarr.${PUBLIC_DOMAIN}/"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/readarr:/config
      - nas:/nas
    restart: unless-stopped
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Readarr"
      - "homepage.description=Book Collection Manager"
      - "homepage.icon=readarr.png"
      - "homepage.href=https://readarr.${PUBLIC_DOMAIN}/"

  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    container_name: lidarr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/lidarr:/config
      - nas:/nas
    restart: unless-stopped
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Lidarr"
      - "homepage.description=Music Collection Manager"
      - "homepage.icon=lidarr.png"
      - "homepage.href=https://lidarr.${PUBLIC_DOMAIN}/"
    
volumes:
  nas:
    external: true

networks:
  default:
  lb-network:
    external: true
