---
version: "3.8"
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    user: "${PUID}:${PGID}"
    networks:
      - default
      - lb-network
    volumes:
      - nas:/nas
      - ${DOCKER_DATA_FOLDER}/komga:/config
    labels:
      - "homepage.group=Media"
      - "homepage.name=Komga"
      - "homepage.description=Manga Collection Manager"
      - "homepage.icon=komga.png"
      - "homepage.href=https://komga.${PUBLIC_DOMAIN}/"
    restart: unless-stopped

volumes:
  nas:
    external: true
    
networks:
  default:
  lb-network:
    external: true