version: '3.8'
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    privileged: true
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "homer.enable=true"
      - "homer.service=Tools"
      - "homer.name=Home Assistant"
      - "homer.subtitle=Home automation service"
      - "homer.logo=assets/tools/homeassistant.png"
      - "homer.target=_blank"
      - "homer.tag=${HOST_TAG}"
      - "homer.url= https://homeassistant.${PUBLIC_DOMAIN}"
    restart: unless-stopped