---
version: '3.3'
services:
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    networks:
      - default
      - lb-network
    volumes:
      - ${DOCKER_DATA_FOLDER}/uptime:/app/data
    restart: unless-stopped
    labels:
      - "homepage.group=Monitoring"
      - "homepage.name=Uptime"
      - "homepage.description=Monitoring status service"
      - "homepage.icon=uptime-kuma.png"
      - "homepage.href=https://uptime.${PUBLIC_DOMAIN}"

networks:
  default:
  lb-network:
    external: true