---
version: "3.8"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    networks:
      - default
      - lb-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "homepage.group=Monitoring"
      - "homepage.name=Dozzle"
      - "homepage.description=Docker Logs Service"
      - "homepage.icon=dozzle.png"
      - "homepage.href=https://dozzle.${PUBLIC_DOMAIN}/"
    restart: unless-stopped
    
networks:
  default:
  lb-network:
    external: true