---
version: "3.8"
services:
  gitea:
    image: gitea/gitea
    container_name: gitea
    networks:
      - default
      - lb-network
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    volumes:
      - ${DOCKER_DATA_FOLDER}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2222:22
    labels:
      - "homepage.group=Tools"
      - "homepage.name=Gitea"
      - "homepage.description=Self-hosted git server"
      - "homepage.icon=gitea.png"
      - "homepage.href=https://git.${PUBLIC_DOMAIN}/"
    restart: unless-stopped

networks:
  default:
  lb-network:
    external: true