version: "3"

services:
  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    container_name: manyfold
    ports:
      - 3214:3214
    volumes:
      - ${DOCKER_DATA_FOLDER}/manyfold/libraries:/libraries
      - nas:/nas
    environment:
      SECRET_KEY_BASE: ${DATABASE_SECRET}
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_USER}?pool=5
    depends_on:
      - db
      - redis
    networks:
      - default
      - lb-network
    links:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: manyfold_db
    volumes:
      - ${DOCKER_DATA_FOLDER}/manyfold/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - default

  redis:
    image: redis:7
    container_name: manyfold_redis
    restart: unless-stopped
    networks:
      - default

volumes:
  nas:
    external: true
    
networks:
  default:
  lb-network:
    external: true