---
version: '3'
services:
  overseerr:
    image: linuxserver/overseerr:develop
    container_name: overseerr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/overseerr:/config
    labels:
      - "homepage.group=PVR"
      - "homepage.name=Overseerr"
      - "homepage.description=Media Requester"
      - "homepage.icon=overseerr.png"
      - "homepage.href=https://overseerr.${PUBLIC_DOMAIN}/"
    restart: unless-stopped

networks:
  default:
  lb-network:
    external: true