---
version: '3'
services:
  overseerr:
    image: linuxserver/overseerr:develop
    container_name: overseerr
    networks:
      - default
      - lb-network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DATA_FOLDER}/overseerr:/config
    labels:
      - "homer.enable=true"
      - "homer.service=PVR"
      - "homer.name=Overseerr"
      - "homer.subtitle=Media Requester"
      - "homer.logo=assets/tools/overseerr.png"
      - "homer.target=_blank"
      - "homer.priority=3"
      - "homer.tag=${HOST_TAG}"
      - "homer.url= https://overseerr.${PUBLIC_DOMAIN}"
    restart: unless-stopped

networks:
  default:
  lb-network:
    external: true