---
version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      - default
      - lb-network
    volumes:
      - ${DOCKER_DATA_FOLDER}/pihole/conf:/etc/pihole/
      - ${DOCKER_DATA_FOLDER}/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      - TZ=${TZ}
    labels:
      - "homer.enable=true"
      - "homer.service=Network"
      - "homer.name=Pi-hole"
      - "homer.subtitle=DNS-level Ad Blocking"
      - "homer.logo=assets/tools/pihole.png"
      - "homer.target=_blank"
      - "homer.priority=3"
      - "homer.tag=${HOST_TAG}"
      - "homer.url=https://pihole.${PUBLIC_DOMAIN}/admin"

      - "homepage.group=Network"
      - "homepage.name=Pi-hole"
      - "homepage.description=DNS-level Ad Blocking"
      - "homepage.icon=pihole.png"
      - "homepage.href=https://pihole.${PUBLIC_DOMAIN}/admin"
    restart: unless-stopped
    
networks:
  default:
  lb-network:
    external: true